version: "3.7"
services:
  scratch-dev:
    image: node:16-alpine3.11
    container_name: scratch-dev
    ports:
      - 3002:3000
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: tail -f /dev/null
